#!/bin/bash
o="randout"
if [[ -z $1 ]]; then
	a=1
	read -p "How many random lines do you want? " i
else
	a=0
	i=$1
fi

while [[ $i -gt 0 ]]; do
	echo $((1 + RANDOM % 500)) >> $o
	i=$(($i - 1))
done
if [[ $a = 1 ]]; then
	echo	"File saved in: ./$o"
	column $o
else
	echo $o
fi
